name: OpenWrt EA0326GMP Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3 python3-distutils \
            rsync unzip zlib1g-dev file wget time ccache swig libelf-dev \
            ecj fastjar subversion pkg-config xsltproc gh

      - name: Clone OpenWrt @ 24.10.2 r28739-d9340319c6
        run: |
          git clone -b v24.10.2 https://github.com/openwrt/openwrt.git

      - name: Add Custom Packages
        run: |
          cd openwrt/package
          git clone https://github.com/jerrykuku/luci-theme-argon.git
          git clone https://github.com/jerrykuku/luci-app-argon-config.git
          git clone https://github.com/sbwml/luci-app-mentohust mentohust

      - name: Load seed.config & update feeds
        run: |
          cd openwrt
          cp ../seed.config .config
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig

      - name: Unlock MTD (remove read-only on BL2/FIP)
        run: |
          cd openwrt
          DTS="target/linux/mediatek/dts/mt7981b-nokia-ea0326gmp.dts"
          cp "$DTS" "$DTS.bak"
          sed -i '/label = "BL2"/,/};/ {/read-only;/d}' "$DTS"
          sed -i '/label = "FIP"/,/};/ {/read-only;/d}' "$DTS"
          diff -u "$DTS.bak" "$DTS" || true

      - name: Download & compile
        run: |
          cd openwrt
          make download -j$(nproc)
          make -j$(nproc) || make -j1 V=s

      - name: Pack filogic directory
        run: |
          cd openwrt/bin/targets/mediatek
          tag="ea0326gmp-$(date +'%Y%m%d')"
          tar -czf ${tag}-filogic.tar.gz filogic/
          mv ${tag}-filogic.tar.gz ../../../../

      - name: Create Release & upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd openwrt
          tag="ea0326gmp-24.10.2-$(date +'%Y%m%d')-$(git rev-parse --short=8 HEAD)"
          gh release create "$tag" \
            --repo="${{ github.repository }}" \
            --title="OpenWrt EA0326GMP Build (${tag#*-})" \
            --notes="Auto-built EA0326GMP firmware with BL2/FIP unlocked and custom packages: Argon theme, Mentohust, sing-box stack." \
            --draft=false \
            --prerelease=false \
            ../ea0326gmp-$(date +'%Y%m%d')-filogic.tar.gz
