name: OpenWrt EA0326GMP (mt7981) - 24.10 r28789-92d4f59709

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3 python3-distutils \
            rsync unzip zlib1g-dev file wget time ccache swig libelf-dev \
            ecj fastjar subversion pkg-config xsltproc

      - name: Clone OpenWrt @ 92d4f59709
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git openwrt
          cd openwrt
          git checkout 92d4f59709

      - name: Copy seed.config & update feeds
        run: |
          cd openwrt
          [ -f ../seed.config ] && cp ../seed.config .config
          make defconfig
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig

      - name: Unlock MTD (remove read-only on BL2/FIP)
        run: |
          set -euxo pipefail
          cd openwrt
          DTS="target/linux/mediatek/dts/mt7981b-nokia-ea0326gmp.dts"
          [ -f "$DTS" ] || { echo "DTS not found"; exit 1; }
          cp "$DTS" "$DTS.bak"
          sed -i '/label = "BL2"/,/};/  {/read-only;/d}'  "$DTS"
          sed -i '/label = "FIP"/,/};/  {/read-only;/d}'  "$DTS"
          echo "==== DTS diff ===="
          diff -u "$DTS.bak" "$DTS" || true

      - name: Download & compile
        run: |
          cd openwrt
          make download -j$(nproc)
          make -j$(nproc) || make -j1 V=s

      - name: Pack entire filogic directory
        run: |
          cd openwrt/bin/targets/mediatek
          tar -czf ea0326gmp-filogic-all.tar.gz filogic/
          mv ea0326gmp-filogic-all.tar.gz ../../../../

      - name: Create Release & upload
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="openwrt-ea0326gmp-24.10-$(git rev-parse --short=8 HEAD)"
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="OpenWrt 24.10 EA0326GMP (${tag#*-})" \
            --notes="Auto-built EA0326GMP images (BL2/FIP unlocked). Includes full filogic folder." \
            --draft=false \
            --prerelease=false \
            ea0326gmp-filogic-all.tar.gz
